apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
    role: hub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-hub
        role: hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:3.7.1
        imagePullPolicy: Always
        ports:
          - containerPort: 4444
            name: http
