apiVersion: v1
kind: Service
metadata:
  namespace: selenium
  name: selenium-hub
  labels:
    app: selenium-hub
    role: hub
spec:
  ports:
  - name: http
    port: 4444
    targetPort: 4444
  selector:
    app: selenium-hub
    role: hub
  type: ClusterIP
  sessionAffinity: None
